# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 468f17bad30bbba82b58581753c2a0c5d84d24097b9ae385f415f83f547c58d6fc8475851a373646ead96be515902a5799286864d3ba8ae769d2b00c59c8389f

test:
  secret_key_base: 6daf09f5ab34faf49b2b891eb5580d3a979db848180f3804b857ee037ea5c3c8c8b361bf84d2b61b4acc8e470061997f8cc505df370f4f1756848c1a5d6779b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
